# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'design.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(574, 588)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.textEditNew = QtWidgets.QTextEdit(self.centralwidget)
        self.textEditNew.setGeometry(QtCore.QRect(10, 30, 291, 241))
        self.textEditNew.setObjectName("textEditNew")
        self.tableWidget = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget.setGeometry(QtCore.QRect(320, 30, 241, 311))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(2)
        self.tableWidget.setRowCount(1)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        self.textEditDiscrip = QtWidgets.QTextEdit(self.centralwidget)
        self.textEditDiscrip.setGeometry(QtCore.QRect(10, 350, 551, 141))
        self.textEditDiscrip.setObjectName("textEditDiscrip")
        self.addOrder = QtWidgets.QPushButton(self.centralwidget)
        self.addOrder.setGeometry(QtCore.QRect(200, 500, 171, 41))
        self.addOrder.setObjectName("addOrder")
        self.newOrder = QtWidgets.QPushButton(self.centralwidget)
        self.newOrder.setGeometry(QtCore.QRect(10, 500, 151, 41))
        self.newOrder.setObjectName("newOrder")
        self.saveOrder = QtWidgets.QPushButton(self.centralwidget)
        self.saveOrder.setGeometry(QtCore.QRect(410, 500, 151, 41))
        self.saveOrder.setObjectName("saveOrder")
        self.orderPrice = QtWidgets.QLineEdit(self.centralwidget)
        self.orderPrice.setGeometry(QtCore.QRect(10, 290, 291, 41))
        self.orderPrice.setObjectName("orderPrice")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 10, 291, 16))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(320, 10, 241, 16))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(10, 270, 291, 21))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(10, 330, 301, 16))
        self.label_4.setObjectName("label_4")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 574, 21))
        self.menubar.setObjectName("menubar")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        self.menu_2 = QtWidgets.QMenu(self.menubar)
        self.menu_2.setObjectName("menu_2")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionBrowse = QtWidgets.QAction(MainWindow)
        self.actionBrowse.setObjectName("actionBrowse")
        self.actionSave = QtWidgets.QAction(MainWindow)
        self.actionSave.setObjectName("actionSave")
        self.actionClose = QtWidgets.QAction(MainWindow)
        self.actionClose.setObjectName("actionClose")
        self.actionClear = QtWidgets.QAction(MainWindow)
        self.actionClear.setObjectName("actionClear")
        self.menu.addAction(self.actionBrowse)
        self.menu.addAction(self.actionSave)
        self.menu.addSeparator()
        self.menu.addAction(self.actionClose)
        self.menu_2.addAction(self.actionClear)
        self.menubar.addAction(self.menu.menuAction())
        self.menubar.addAction(self.menu_2.menuAction())

        self.retranslateUi(MainWindow)
        self.actionClose.triggered.connect(MainWindow.close)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        item = self.tableWidget.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "1"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Название"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Цена"))
        self.addOrder.setText(_translate("MainWindow", "Добавить товар в заказ"))
        self.newOrder.setText(_translate("MainWindow", "Новый заказ"))
        self.saveOrder.setText(_translate("MainWindow", "Сохранить заказ"))
        self.label.setText(_translate("MainWindow", "Заказ:"))
        self.label_2.setText(_translate("MainWindow", "Товары:"))
        self.label_3.setText(_translate("MainWindow", "Итоговая стоимость заказа:"))
        self.label_4.setText(_translate("MainWindow", "Описание товара:"))
        self.menu.setTitle(_translate("MainWindow", "Файл"))
        self.menu_2.setTitle(_translate("MainWindow", "Поля"))
        self.actionBrowse.setText(_translate("MainWindow", "Открыть"))
        self.actionSave.setText(_translate("MainWindow", "Сохранить"))
        self.actionClose.setText(_translate("MainWindow", "Закрыть"))
        self.actionClear.setText(_translate("MainWindow", "Очистить"))

